import { useEffect, useRef, useState, useCallback } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import StageSurface from '../world/StageSurface.jsx'
import { COLORS, FONTS } from '../score/tokens'
import { appendEntry, getIsFirstSession } from '../lib/sessionStore.js'
import StemPlayer from '../lib/stemPlayer.js'
import { fireMoment, resetMoments } from '../lib/momentBus.js'
import { advanceFormationStage, resetFormationStage } from '../lib/formationStage.js'
import QuestionDisplay from './QuestionDisplay'
import { useAdmirerRoom } from '../hooks/useAdmirerRoom.js'
import { SPEAKING_DUCK } from '../orchestra/AdmirerRoom.js'
import { getAvd, resetAvd } from '../lib/avdStore.js'
import { mapAvdToStems } from '../lib/avdToStems.js'
import { startGenerativeTrack, LIVE_MUSIC_GEN_ENABLED, GEN_BLOOM_WAIT_MS } from '../lib/musicGen.js'
import { avdRecorder } from '../lib/avdRecorder.js'
import { buildSessionRecord } from '../lib/sessionRecord.js'
import { putAudio } from '../lib/archive.js'
import { useAttunementScore } from '../hooks/useAttunementScore.js'
import { archetypeRing } from '../lib/archetypeRing.js'
import LeanLift from './attunement/LeanLift'
import Rise from './attunement/Rise'
import Face from './attunement/Face'
import Listen from './attunement/Listen'
import EraSearch from './attunement/EraSearch'
import { FRAGMENTS } from '../lib/fragmentBank.js'
import { allClipIds, mirrorClipId, readingClipId, mirrorText, readingText } from '../lib/reflectionScript.js'
import { allClipIds as prompterClipIds, sealClipId } from '../lib/prompterScript.js'
import { getReflection, resetReflection } from '../lib/reflectionState.js'
import { setEra, getEra, resetEra } from '../lib/eraSelection.js'
import { NOCTURNE_ENABLED } from '../world/flags.js'
import { pushTraceStroke } from '../world/worldStore.js'
import { playSfx } from '../world/worldSound.js'

// The Admirer's spoken lines are pre-baked TTS clips in public/admirer/voice/
// (generated by scripts/generate-admirer-voice.js with the Admirer voice).
// Only lines listed here have a clip on disk; others are skipped silently so
// the on-screen movement cues still carry the prompt. The live ElevenLabs agent
// has been fully removed. Includes the welcome (+ its 3 paced segments + the
// returning-user line), the 18 reflection clips, and the Prompter's spoken
// score (the per-beat asks + seals + transitions — see lib/prompterScript.js).
// Listing an id here only means "try to play it": if the mp3 isn't on disk yet
// the fetch/decode fails and playVoiceLine's catch resolves silently, leaving
// the beat's on-screen cue to carry the prompt.
const AVAILABLE_VOICE_LINES = new Set([
  'welcome', 'welcome-1', 'welcome-2', 'welcome-3', 'welcome-return',
  ...allClipIds(),
  ...prompterClipIds(),
])

// The first-time welcome, paced into three segments played in sequence (see
// the arrival choreography below) instead of as one ~25s monologue. Same
// wording as the single `welcome` clip (kept on disk for backward-compat),
// just partitioned at sentence boundaries.
const WELCOME_SEGMENTS = ['welcome-1', 'welcome-2', 'welcome-3']
// A short beat between segments (not a long pause — there's no ambient bed
// under arrival, so a longer gap reads as dead air), and a slight room widen on
// each. Both intentionally small: arrival's own expansion target is 0 (still
// intimate), reached properly when the score's advance() fires on the last end.
const WELCOME_PAUSE_MS = 300
const WELCOME_WIDEN_STEP = 0.05

// How long after a beat's commit-sfx the Prompter's transfer line lands. Long
// enough that the resonator/pizzicato has bloomed and the line reads as a
// response to it rather than a layer on top of it.
const SEAL_LINE_DELAY_MS = 900

// The Admirer phase. Voice is pre-baked TTS clips played through the HRTF room
// (no live agent). Kept as an inner component for a stable single mount point.
function AdmirerInner({ onNext, getAudioCtx, revealAudioRef }) {
  const [hasError, setHasError] = useState(false)
  // FIX 1 — tap-to-continue escape hatch for the arrival beat.
  const [showArrivalContinue, setShowArrivalContinue] = useState(false)
  const stemsBundleRef = useRef(null)
  const playerRef = useRef(null)
  // Generative path (flag-gated by VITE_ENABLE_LIVE_MUSIC_GEN). genPromiseRef
  // holds the in-flight per-session generation; genPlayerRef the resolved,
  // started-silent GenerativePlayer. When the flag is off, both stay null and
  // every path below is the unchanged catalog-stem flow.
  const genPromiseRef = useRef(null)
  const genPlayerRef = useRef(null)
  // Set once the generative track can no longer win (the catalog committed at
  // bloom, or the rite unmounted). Generation takes ~18–21s but the bloom wait
  // is only 4s, so a generation almost always resolves AFTER the seam has moved
  // on; without this guard its .then would start() an orphaned, forever-looping
  // player that nothing stops. When cancelled, the late resolve stops itself.
  const genCancelledRef = useRef(false)
  // Idempotency guard for the orchestra handoff. The score's bloom is the
  // intended trigger; this also makes a stray agent commitEntry call a no-op
  // so the record is persisted and onNext fires exactly once.
  const committedRef = useRef(false)

  // Monotonic token so the last-requested load wins; superseded in-flight
  // loads self-abandon (no orphan started players).
  const loadTokenRef = useRef(0)

  // Load the matched song's stems silently in the background so the Orchestra
  // can pick them up via revealAudioRef without an audio gap. Race-safe: the
  // last call wins; an earlier call that resolves after a newer one has started
  // abandons itself without starting or writing anything.
  const loadStemsSilently = useCallback(async (bundle) => {
    const ctx = getAudioCtx?.()
    if (!ctx) {
      console.warn('[attunement] no audio context — orchestra will fall back to static track')
      return
    }
    const token = ++loadTokenRef.current
    const prev = playerRef.current
    try {
      const player = await StemPlayer.load(ctx, bundle.stems, bundle.masterUrl)
      // A newer load was requested while we were decoding — abandon this one.
      // It was never start()ed, so it has no live audio graph to tear down.
      if (token !== loadTokenRef.current) return
      // Stop the previously-started player (if any) before replacing it.
      if (prev && prev !== player) {
        try { prev.stop?.() } catch { /* ignore */ }
      }
      player.setVolume(0, 0)
      player.start()
      playerRef.current = player
      stemsBundleRef.current = bundle
      if (revealAudioRef) revealAudioRef.current = player
    } catch (e) {
      console.warn('[attunement] StemPlayer.load failed:', e)
    }
  }, [getAudioCtx, revealAudioRef])

  // Speculative silent pre-load during Rise: load the nearest archetype's
  // stems as the in-progress vector resolves. If Face later changes the
  // archetype, onBloom reloads. Skips when the archetype hasn't changed.
  const preloadArchetypeRef = useRef(null)
  const onSpeculativePreload = useCallback((archetypeId) => {
    if (preloadArchetypeRef.current === archetypeId) return
    preloadArchetypeRef.current = archetypeId
    loadStemsSilently(mapAvdToStems(getAvd(), { era: getEra() }))
  }, [loadStemsSilently])

  // Era-commit → fire per-session generative music (flag-gated). By this beat
  // `face` has fixed the archetype (the AVD vector is hard-snapped to its
  // centroid) and `era` fixes the decade, so the composition plan has all it
  // needs. The result becomes the Act1→Act2 handoff at bloom IF it's ready;
  // otherwise the speculative catalog player (loaded at Rise) is the fallback,
  // so the sacred seam never waits on the network. Fires at most once.
  const maybeStartGeneration = useCallback(() => {
    if (!LIVE_MUSIC_GEN_ENABLED || genPromiseRef.current) return
    const ctx = getAudioCtx?.()
    if (!ctx) return
    const archetypeId = mapAvdToStems(getAvd(), { era: getEra() }).archetypeId
    const p = startGenerativeTrack({ ctx, avd: getAvd(), archetypeId, eraYear: getEra() })
    genPromiseRef.current = p
      ? p.then((player) => {
          if (!player) return null
          // Late-arriving orphan guard: if the seam already moved on (catalog
          // won at bloom, or the rite was abandoned), stop this player now
          // instead of leaking a forever-looping graph.
          if (genCancelledRef.current) {
            try { player.stop?.() } catch { /* ignore */ }
            return null
          }
          genPlayerRef.current = player
          return player
        })
      : null
  }, [getAudioCtx])

  // When the score finalizes, build + persist the rich session record, then
  // hand off to orchestra. The 600ms delay lets the bloom's expansion ramp
  // breathe before the phase swaps.
  const onCommitEntry = useCallback((entry) => {
    if (committedRef.current) return
    committedRef.current = true
    try {
      const rec = avdRecorder.isRecording() ? avdRecorder.stop(Date.now()) : null
      const bundle = stemsBundleRef.current
      const record = buildSessionRecord({
        startedAt: rec?.startedAt ?? Date.now(),
        endedAt: rec?.endedAt ?? Date.now(),
        finalVector: rec?.finalVector ?? getAvd(),
        avdTrajectory: rec?.trajectory ?? [],
        landing: bundle ? { archetypeId: bundle.archetypeId, variationId: bundle.variationId, mode: bundle.mode } : null,
        summary: entry?.summary || '',
        rand: Math.random(),
      })
      appendEntry(record)
      // If the winning track was generated, persist its raw bytes locally under
      // the same session id (fire-and-forget; degrades gracefully without
      // IndexedDB). Then free the ~MBs of retained bytes.
      const gp = genPlayerRef.current
      if (gp && gp.encodedBytes && revealAudioRef?.current === gp) {
        try {
          putAudio(record.id, new Blob([gp.encodedBytes], { type: 'audio/mpeg' })).catch(() => {})
        } catch { /* IndexedDB unavailable */ }
        gp.releaseEncoded()
      }
    } catch (e) {
      console.warn('[attunement] session record persist failed', e)
    }
    setTimeout(() => {
      // Carry the Admirer's one-line summary forward so App can relay it in
      // the entry message at settle.
      onNext({ stemsBundle: stemsBundleRef.current, summary: entry?.summary })
    }, 600)
  }, [onNext, revealAudioRef])

  // Whether a pre-baked voice clip is currently playing. Drives the amber dot
  // pulse + the "speaking" state label (replaces the old SDK isSpeaking).
  const [speaking, setSpeaking] = useState(false)
  // The end-of-Act-1 reflection caption (the spoken text, shown on screen).
  const [reflectionCaption, setReflectionCaption] = useState(null)

  // Build A — the spatial room. Plays the Admirer's pre-baked voice clips +
  // the per-movement multi-source playback through an HRTF room. The score
  // drives the room open (setExpansion per movement, beginExpansion at bloom).
  const { beginExpansion, setExpansion, getRoom } = useAdmirerRoom({ getAudioCtx })

  // Play one of the Admirer's pre-baked voice lines through the room. Lines not
  // present in AVAILABLE_VOICE_LINES (no clip on disk yet) resolve immediately
  // so callers/sequences never stall — the on-screen movement cue carries the
  // prompt in that case. onEnded always fires exactly once.
  // `onStart` fires ONLY when a clip actually reaches the room — i.e. the mp3
  // existed, decoded, and is now sounding. Callers use it to tell "the Prompter
  // spoke" apart from "there was nothing to say", which is what decides whether
  // the on-screen cue is allowed to fade (see onScoreAsk).
  const playVoiceLine = useCallback((lineId, { onEnded, onStart } = {}) => {
    const room = getRoom?.()
    const ctx = getAudioCtx?.()
    if (!room || !ctx || !AVAILABLE_VOICE_LINES.has(lineId)) { onEnded?.(); return }
    let settled = false
    const finish = () => { if (settled) return; settled = true; setSpeaking(false); onEnded?.() }
    fetch(`/admirer/voice/${lineId}.mp3`)
      .then((r) => r.arrayBuffer())
      .then((b) => ctx.decodeAudioData(b))
      .then((buf) => {
        setSpeaking(true)
        onStart?.()
        room.playVoiceClip(buf, { onEnded: finish })
      })
      .catch((e) => { console.warn('[admirer] voice line failed:', lineId, e); finish() })
  }, [getRoom, getAudioCtx])

  // Score → room expansion: each committed movement nudges the room a notch.
  const onScoreExpansion = useCallback((t) => { setExpansion(t) }, [setExpansion])

  // Score → room reaction. The only audible reaction kept is the Rise
  // down-stroke transient (markBeat); spoken reactions are gone with the agent.
  const onScoreReact = useCallback((movementId, payload) => {
    if (movementId === 'rise' && payload.downbeat) {
      roomHandleRef.current?.markBeat?.(payload.intensity ?? 1)
    }
  }, [])

  // Score → asking: when a movement begins, the Prompter voices that beat's
  // invitation (lib/prompterScript.js ASKS, baked as `ask-<movementId>.mp3`).
  //
  // This is the audio-first turn: the spoken line, not the screen, is what
  // teaches the gesture. So once the line has FINISHED we dim the beat's
  // written instruction — the long affordance sentence and the phone pictogram —
  // and leave the listener with the light, the bed, and their own hands.
  //
  // The fail-safe is the whole point: `cueDimmed` is only ever set true after
  // onStart confirmed a clip actually sounded. A missing or undecodable mp3
  // means the room said nothing, so the full written cue stays on screen and
  // the beat is exactly as discoverable as it is today.
  const [cueDimmed, setCueDimmed] = useState(false)
  const askSpokeRef = useRef(false)
  const onScoreAsk = useCallback((movementId) => {
    // New beat: the previous beat's dim never carries over.
    setCueDimmed(false)
    askSpokeRef.current = false
    playVoiceLine(`ask-${movementId}`, {
      onStart: () => { askSpokeRef.current = true },
      onEnded: () => { if (askSpokeRef.current) setCueDimmed(true) },
    })
  }, [playVoiceLine])

  // Score → bloom (the act-1 → act-2 handoff). Ensure the faced archetype's
  // stems are the loaded ones, snap the geometry fully formed, animate the
  // room open, then build + persist the record and hand off to Orchestra
  // (reusing onCommitEntry's body — the seam the Orchestra depends on).
  // FIX 2 — async: await the load so the 600ms onNext can't race a slow reload.
  const onBloom = useCallback(async () => {
    // Nocturne (canon §5) — the signature seam: as light + reverb widen into the
    // hall, a diegetic "small room opening" swells under it. Fire-and-forget +
    // fail-silent, so it can never perturb the sacred handoff below.
    if (NOCTURNE_ENABLED) playSfx('lamp-wide', { volume: 0.5 })
    // Generative winner path (flag-gated). If a generation is in flight, give it
    // a bounded window to finish; if it resolves to a live player, it becomes
    // the handoff and the speculative catalog player is stopped. Any timeout or
    // failure falls straight through to the catalog path below — the seam never
    // blocks on the network.
    if (LIVE_MUSIC_GEN_ENABLED && genPromiseRef.current) {
      const genPlayer = await Promise.race([
        genPromiseRef.current,
        new Promise((resolve) => setTimeout(() => resolve(null), GEN_BLOOM_WAIT_MS)),
      ]).catch(() => null)
      if (genPlayer && genPlayerRef.current === genPlayer) {
        // Generated track won. Invalidate any STILL-IN-FLIGHT speculative catalog
        // load (loadStemsSilently checks this token) so it can't resolve later and
        // clobber the generated winner as the handoff. Then stop the already-
        // started catalog player so two graphs don't run, and hand off the generated one.
        loadTokenRef.current++
        const cat = playerRef.current
        if (cat && cat !== genPlayer) { try { cat.stop?.() } catch { /* ignore */ } }
        if (revealAudioRef) revealAudioRef.current = genPlayer
        stemsBundleRef.current = { ...mapAvdToStems(getAvd(), { era: getEra() }), mode: 'generated' }
        fireMoment(1.0, 'startGeneration')
        advanceFormationStage(2)
        beginExpansion()
        onCommitEntry({ summary: '' })
        return
      }
      // Catalog wins — a generation still in flight must not later start() an
      // orphan player once it resolves. Its .then reads this and stops itself.
      genCancelledRef.current = true
      // else: not ready / failed — fall through to the catalog path.
    }

    const bundle = mapAvdToStems(getAvd(), { era: getEra() })
    // Gate the commit on the load so the 600ms onNext can't race a slow
    // reload (which would let Orchestra detach a stale/empty player). Reload on
    // EITHER a different archetype OR a different variation — the era beat can
    // change the variation within the same world (the speculative preload had
    // no era, so it loaded the world's default version).
    const need = stemsBundleRef.current
    const needLoad = !playerRef.current
      || bundle.archetypeId !== need?.archetypeId
      || bundle.variationId !== need?.variationId
    if (needLoad) await loadStemsSilently(bundle)
    // Editorial moment: snap to fully formed; front figure fades in over the
    // handoff. eventIds keep both safe against re-fire.
    fireMoment(1.0, 'startGeneration')
    advanceFormationStage(2)
    beginExpansion()
    onCommitEntry({ summary: '' })
  }, [loadStemsSilently, beginExpansion, onCommitEntry, revealAudioRef])

  const score = useAttunementScore({
    onExpansion: onScoreExpansion,
    onSpeculativePreload,
    onBloom,
    onReact: onScoreReact,
    onAsk: onScoreAsk,
  })

  // Nocturne — the Trace, written in Act I (canon §7). Each committed gesture
  // beat leaves a persistent stroke on the WorldStage: the listener watches
  // their taste written in light, and at bloom the accumulated trace is what
  // they conduct with. Purely ADDITIVE + gated: it reads the already-committed
  // AVD vector (getAvd, signed a·v·d) when the score ADVANCES past a gesture
  // beat and writes a stroke to worldStore — it never touches the choreography
  // (useAttunementScore / attunement* are read-only). Position mirrors the
  // constellation mapping: valence→x, arousal→y (high arousal higher). One
  // stroke per gesture beat (leanLift, listen, rise, face).
  const prevMovementIdRef = useRef(null)
  const traceBeatsRef = useRef(new Set())
  const sealTimersRef = useRef([])
  useEffect(() => {
    if (!NOCTURNE_ENABLED) return
    const curId = score.movement?.id || null
    const prevId = prevMovementIdRef.current
    prevMovementIdRef.current = curId
    // Diegetic beat-entry cues (canon §5): the pool tips as a tilt beat opens;
    // the six worlds ring in on face. Fail-silent, once per entry.
    if (curId && curId !== prevId) {
      if (curId === 'face') playSfx('world-face', { volume: 0.4 })
      else if (curId === 'leanLift' || curId === 'listen') playSfx('pool-tip', { volume: 0.35 })
    }
    const GESTURE_BEATS = new Set(['leanLift', 'listen', 'rise', 'face'])
    // The beat we just LEFT committed its gesture — seal a stroke for it once.
    if (prevId && prevId !== curId && GESTURE_BEATS.has(prevId) && !traceBeatsRef.current.has(prevId)) {
      traceBeatsRef.current.add(prevId)
      const { a, v } = getAvd()
      const av = Math.max(-1, Math.min(1, Number.isFinite(a) ? a : 0))
      const vv = Math.max(-1, Math.min(1, Number.isFinite(v) ? v : 0))
      pushTraceStroke({ x: (vv + 1) / 2, y: 1 - (av + 1) / 2, size: (av + 1) / 2, kind: prevId, beat: prevId })
      // A diegetic seal from the room (canon §5): a warm resonator for the
      // valence/arousal beats, a deep pizzicato for the depth/facing beats.
      playSfx((prevId === 'leanLift' || prevId === 'rise') ? 'beat-commit-warm' : 'beat-commit-deep')
      // …and then the Prompter's transfer line (canon §8) — the moment the
      // listener is told their gesture was KEPT ("the orchestra will remember
      // this lean."). Delayed past the sfx so the two don't stack on the same
      // instant; fail-silent like every other voice line, so a missing clip
      // simply leaves the seal wordless.
      const t = setTimeout(() => playVoiceLine(sealClipId(prevId)), SEAL_LINE_DELAY_MS)
      sealTimersRef.current.push(t)
    }
  }, [score.movement?.id, playVoiceLine])

  // Clear any pending seal-line timer on unmount so a late line can't fire into
  // a torn-down room (the phase swap at bloom is the case that matters).
  useEffect(() => () => {
    for (const t of sealTimersRef.current) clearTimeout(t)
    sealTimersRef.current = []
  }, [])

  // Arrival choreography: footsteps walk up (far → close), then the Admirer
  // speaks — the full welcome (paced into 3 segments) for a first-time
  // listener, or a short recognition line for a returning one — then we
  // advance into the first movement (leanLift). Gated on the room being
  // live — getRoom() is null until the room's build effect runs, so we retry
  // briefly. The footsteps fetch+decode is kicked off immediately, in
  // parallel with that retry poll, rather than serialized after it (the
  // context already exists by the time Admirer mounts — see Entry.score.jsx's
  // "begin" tap — so there's no reason to make the network round-trip wait
  // its turn). Runs once.
  const arrivalStartedRef = useRef(false)
  const arrivalAdvancedRef = useRef(false)
  const advanceRef = useRef(null)
  useEffect(() => { advanceRef.current = score.advance })
  useEffect(() => {
    let cancelled = false
    let tries = 0
    let timer = null
    let pauseTimer = null

    // Nocturne (canon §5) — the room's door. The listener has just crossed from
    // the Overture into the Attunement Room, and until now that crossing was
    // silent: the far hall door opens onto the quiet room, and only THEN do the
    // footsteps start toward the seat. Fires once (this effect runs once) and
    // is fail-silent, so it can never delay the arrival choreography below.
    if (NOCTURNE_ENABLED) playSfx('threshold', { volume: 0.4 })

    // Start the network fetch early (no ctx needed) so it overlaps the room
    // poll; DECODE with the confirmed ctx inside begin(). Capturing the ctx here
    // would pin footsteps to null whenever the ctx isn't ready at mount (e.g. the
    // ?phase=admirer dev route, where audio inits a beat after this effect runs).
    const footstepsBytes = fetch('/admirer/footsteps.mp3')
      .then((r) => r.arrayBuffer())
      .catch(() => null) // no footsteps clip — still proceed to voice

    const begin = () => {
      if (cancelled || arrivalStartedRef.current) return
      const room = getRoom?.()
      const ctx = getAudioCtx?.()
      if (!room || !ctx) {
        // Was up to 4s (40×100ms); the room is built synchronously on mount
        // so this virtually never has to wait — tightened to a ~1.5s ceiling
        // that still gives slow devices room before the escape hatch shows.
        if (tries++ < 30) timer = setTimeout(begin, 50)
        else setHasError(true)
        return
      }
      arrivalStartedRef.current = true
      // One-shot: arrival advances exactly once, whether via the last welcome
      // segment or the escape hatch. Without this, an orphaned segment finishing
      // AFTER an escape tap would re-fire advance() against the CURRENT beat
      // (leanLift), force-skipping it without writing its gesture taste.
      const finishArrival = () => {
        if (cancelled || arrivalAdvancedRef.current) return
        arrivalAdvancedRef.current = true
        advanceRef.current?.()
      }

      // Play the paced welcome segments in sequence, with a brief pause + a
      // slight room widen between each — so the 25s monologue reads as a
      // reveal. The final segment finishes into leanLift via finishArrival.
      const playSegment = (i) => {
        if (cancelled) return
        if (i >= WELCOME_SEGMENTS.length) {
          // Canon §8 — the Prompter names its own role once, on a first
          // session only, after the welcome has landed. finishArrival() is
          // reached either way (playVoiceLine always settles onEnded, whether
          // the clip played or was absent), so the arc can never stall here.
          playVoiceLine('prompter-intro', { onEnded: finishArrival })
          return
        }
        playVoiceLine(WELCOME_SEGMENTS[i], {
          onEnded: () => {
            if (cancelled) return
            if (i < WELCOME_SEGMENTS.length - 1) {
              setExpansion(WELCOME_WIDEN_STEP * (i + 1))
              pauseTimer = setTimeout(() => playSegment(i + 1), WELCOME_PAUSE_MS)
            } else {
              playSegment(i + 1)
            }
          },
        })
      }

      const toWelcome = () => {
        if (cancelled) return
        fireMoment(0.12, 'welcome')
        // Returning listeners skip the full welcome for a short recognition
        // line instead — they already know what this room is.
        if (getIsFirstSession()) playSegment(0)
        else playVoiceLine('welcome-return', { onEnded: finishArrival })
      }

      footstepsBytes
        .then((b) => (b && !cancelled ? ctx.decodeAudioData(b) : null))
        .catch(() => null)
        .then((buf) => {
          if (cancelled) return
          if (buf) room.playFootsteps(buf, { onEnded: toWelcome })
          else toWelcome()
        })
    }
    begin()
    return () => {
      cancelled = true
      if (timer) clearTimeout(timer)
      if (pauseTimer) clearTimeout(pauseTimer)
    }
  }, [getRoom, getAudioCtx, playVoiceLine, setExpansion])

  // End-of-Act-1 reflection: on entering the 'reflect' beat, narrate the mirror
  // (what the listener's body chose) then the faced world's reading, then
  // advance into bloom. Two pre-baked clips stitched at a sentence boundary; the
  // caption shows the spoken text. Runs once. Deferred via setTimeout(0) so no
  // synchronous setState in the effect body (react-hooks lint).
  const reflectStartedRef = useRef(false)
  useEffect(() => {
    if (score.movement?.id !== 'reflect' || reflectStartedRef.current) return
    reflectStartedRef.current = true
    let cancelled = false
    const t = setTimeout(() => {
      if (cancelled) return
      const r = getReflection()
      const warmth = r.warmth || 'warm'
      const depth = r.depth || 'open'
      const energy = r.energy || 'low'
      const world = r.world || 'hearth-keeper'
      setReflectionCaption(mirrorText(warmth, depth, energy))
      // Canon §8 — the Prompter opens the reflection ("here is what your hands
      // just wrote.") before the mirror itself. Chained through onEnded so the
      // two never overlap; an absent clip settles immediately and the mirror
      // follows exactly as it does today.
      playVoiceLine('reflect-open', { onEnded: () => {
      if (cancelled) return
      playVoiceLine(mirrorClipId(warmth, depth, energy), {
        onEnded: () => {
          if (cancelled) return
          setReflectionCaption(readingText(world))
          playVoiceLine(readingClipId(world), {
            onEnded: () => { if (!cancelled) advanceRef.current?.() },
          })
        },
      })
      } })
    }, 0)
    return () => { cancelled = true; clearTimeout(t) }
  }, [score.movement?.id, playVoiceLine])

  // Arrival escape hatch: a low-emphasis "continue" appears only as a safety
  // net — immediately on error, or if the welcome hasn't advanced us out of
  // arrival after a generous wait — so the arc can never permanently stall.
  // setState is deferred via setTimeout to satisfy react-hooks/set-state-in-effect.
  useEffect(() => {
    const movId = score.movement?.id
    if (movId !== 'arrival') {
      const t = setTimeout(() => setShowArrivalContinue(false), 0)
      return () => clearTimeout(t)
    }
    if (hasError) {
      const t = setTimeout(() => setShowArrivalContinue(true), 0)
      return () => clearTimeout(t)
    }
    // 40s ceiling: footsteps (now up to ~8s, was 3s) + the 3 paced welcome
    // segments (same total speech as the old single clip, plus 2 short
    // between-segment pauses) can run closer to 34s than the old ~28s total,
    // so this needed headroom above the old 32000.
    const t = setTimeout(() => setShowArrivalContinue(true), 40000)
    return () => clearTimeout(t)
  }, [score.movement?.id, hasError])

  // Per-movement room playback: start/stop the right multi-source handle as
  // the movement changes. Fragment masters stand in as textures for the Lean
  // pair / Face ring / Rise bed (assets refined later — spec §11).
  const roomHandleRef = useRef(null)
  useEffect(() => {
    const room = getRoom()
    const ctx = getAudioCtx?.()
    if (!room || !ctx) return undefined
    let cancelled = false
    const decode = (url) => fetch(url).then((r) => r.arrayBuffer()).then((b) => ctx.decodeAudioData(b))

    const start = async () => {
      try {
        if (score.movement?.id === 'leanLift') {
          const [l, r] = await Promise.all([
            decode(FRAGMENTS[2].url), // shadow-piano-late (cold)
            decode(FRAGMENTS[0].url), // warm-acoustic-now (warm)
          ])
          if (cancelled) return
          roomHandleRef.current = room.playTexturePair(l, r)
        } else if (score.movement?.id === 'listen') {
          const bed = await decode(FRAGMENTS[1].url) // a world fragment to shape
          if (cancelled) return
          roomHandleRef.current = room.playFilteredBed(bed)
        } else if (score.movement?.id === 'rise') {
          const bed = await decode(FRAGMENTS[4].url) // lifted-cinematic
          if (cancelled) return
          roomHandleRef.current = room.playRiseBed(bed)
        } else if (score.movement?.id === 'face') {
          const ring = archetypeRing()
          const entries = await Promise.all(ring.map(async (rr, i) => ({
            azimuthDeg: rr.azimuthDeg,
            buffer: await decode(FRAGMENTS[i % FRAGMENTS.length].url),
          })))
          if (cancelled) return
          roomHandleRef.current = room.playRingSources(entries)
        }
      } catch (e) {
        console.warn('[attunement] room playback failed for', score.movement?.id, e)
      }
    }
    start()
    return () => {
      cancelled = true
      try { roomHandleRef.current?.stop() } catch { /* ignore */ }
      roomHandleRef.current = null
    }
  }, [score.movement?.id, getRoom, getAudioCtx])

  // Whether the Prompter is currently speaking, readable from the per-frame
  // loop below (which is where ducking is applied — see there for why).
  const speakingRef = useRef(false)
  useEffect(() => { speakingRef.current = speaking }, [speaking])
  // The duck value last written to the active handle (null = nothing written
  // yet for this handle), so the per-frame loop only ramps on a change.
  const appliedDuckRef = useRef(null)

  // Drive the active room handle from the live gesture each frame.
  useEffect(() => {
    let raf = 0
    let mounted = true
    const tick = () => {
      if (!mounted) return
      const h = roomHandleRef.current
      if (h) {
        if (score.movement?.id === 'leanLift' && h.setBalance) {
          // Post-commit, hold the crossfade at the chosen side so a relaxing
          // wrist doesn't slide the warm/cold balance back toward center.
          const cb = score.live.current.committedBalance
          if (typeof cb === 'number') h.setBalance(Math.sign(cb) || 0)
          else h.setBalance((score.live.current.pan - 0.5) * 2)
        }
        if (score.movement?.id === 'listen' && h.setBrightness) {
          // Tilt forward (low filterNorm) DARKENS the bed — matching the
          // Orchestra (beta → filter cutoff). Post-commit hold it at the chosen
          // extreme so a relaxing wrist doesn't drift the brightness.
          const cbr = score.live.current.committedBrightness
          if (typeof cbr === 'number') h.setBrightness(cbr)
          else h.setBrightness(score.live.current.filterNorm ?? 0.5)
        }
        // FIX 3 — drive Rise audio reactivity each frame.
        if (score.movement?.id === 'rise' && h.setSwell) {
          h.setSwell(score.live.current.swell ?? 0)
        }
        if (score.movement?.id === 'face' && h.spotlight) {
          h.spotlight(score.live.current.relYaw)
        }
        // Duck the bed while the Prompter speaks over it, lift it back when the
        // line ends. The beds are the room, not background music — they never
        // stop, they only make space. Applied here rather than in an effect
        // because the handle is created asynchronously (the bed has to fetch +
        // decode first), so a beat whose line starts before its bed is ready
        // would otherwise come up un-ducked. Only written on CHANGE, so this
        // costs one ref compare per frame and schedules no ramps at rest.
        const wantDuck = speakingRef.current ? SPEAKING_DUCK : 1
        if (h.setDuck && appliedDuckRef.current !== wantDuck) {
          appliedDuckRef.current = wantDuck
          try { h.setDuck(wantDuck) } catch { /* never break the beat */ }
        }
      } else {
        // No handle yet (or the beat ended) — forget what we applied so the
        // next bed gets an explicit write rather than inheriting this state.
        appliedDuckRef.current = null
      }
      raf = requestAnimationFrame(tick)
    }
    raf = requestAnimationFrame(tick)
    return () => { mounted = false; cancelAnimationFrame(raf) }
  }, [score.movement?.id, score.live])

  // Editorial moment dispatcher + session lifecycle. Each rite starts with
  // the release at 0 (resetMoments) plus an immediate 8% pre-release. The
  // 'mount' eventId makes this idempotent. Also resets the AVD vector and
  // starts the ~1Hz AVD trajectory recorder; cleanup stops it + resets.
  useEffect(() => {
    resetMoments()
    resetFormationStage()
    resetReflection()
    resetEra()
    fireMoment(0.08, 'mount')
    resetAvd()
    avdRecorder.start(Date.now())
    return () => {
      if (avdRecorder.isRecording()) avdRecorder.stop(Date.now())
      resetAvd()
    }
  }, [])

  // Stop the orphan StemPlayer on unmount if the rite was abandoned.
  useEffect(() => {
    return () => {
      // A generation still in flight at unmount must stop itself when it later
      // resolves (its .then reads this) — otherwise it starts an orphan graph.
      genCancelledRef.current = true
      // Never stop the WINNER on a committed bloom — it's the live handoff.
      // Orchestra mounts next (AnimatePresence mode="wait" unmounts us first)
      // and calls detachAndGetSources() on revealAudioRef.current; stopping it
      // here nulls its sources and the song dies at the seam.
      const cat = playerRef.current
      const gen = genPlayerRef.current
      if (!committedRef.current) {
        // Abandoned rite — stop every player we started so nothing keeps running.
        if (cat && revealAudioRef?.current === cat) {
          try { cat.stop?.() } catch { /* ignore */ }
        }
        if (gen && gen !== cat) { try { gen.stop?.() } catch { /* ignore */ } }
        if (revealAudioRef && (revealAudioRef.current === cat || revealAudioRef.current === gen)) {
          revealAudioRef.current = null
        }
      } else {
        // Committed — revealAudioRef.current is the winner (Orchestra owns it).
        // Stop only the LOSER so it doesn't keep running silently.
        const winner = revealAudioRef?.current
        if (cat && cat !== winner) { try { cat.stop?.() } catch { /* ignore */ } }
        if (gen && gen !== winner) { try { gen.stop?.() } catch { /* ignore */ } }
      }
      playerRef.current = null
      genPlayerRef.current = null
    }
  }, [])

  // Derive the visible state label from voice playback + the active movement.
  const movementId = score.movement?.id
  let stateLabel
  let stateKey
  if (hasError) {
    // "the Prompter" — canon §8's rename. This is the one user-VISIBLE place
    // the role was still called the Admirer, which would now contradict the
    // spoken prompter-intro line.
    stateLabel = 'the prompter could not arrive. try again later.'
    stateKey = 'error'
  } else if (movementId === 'era') {
    // The search beat has its own prompt; keep the top label quiet.
    stateLabel = ''
    stateKey = 'era'
  } else if (movementId === 'reflect') {
    // The reflection caption carries the words; keep the label quiet.
    stateLabel = ''
    stateKey = 'reflect'
  } else if (speaking) {
    stateLabel = 'speaking'
    stateKey = 'speaking'
  } else if (movementId === 'arrival') {
    // The Admirer is walking up / about to speak the welcome.
    stateLabel = 'arriving'
    stateKey = 'arriving'
  } else if (movementId === 'leanLift') {
    stateLabel = 'lean toward what pulls'
    stateKey = 'leanLift'
  } else if (movementId === 'listen') {
    stateLabel = 'listen'
    stateKey = 'listen'
  } else if (movementId === 'rise') {
    stateLabel = 'let it rise'
    stateKey = 'rise'
  } else if (movementId === 'face') {
    stateLabel = 'face the room'
    stateKey = 'face'
  } else {
    // bloom / handoff — fall silent
    stateLabel = ''
    stateKey = 'bloom'
  }

  return (
    <StageSurface>
      <div style={{
        position: 'absolute', inset: 0,
        display: 'flex', flexDirection: 'column',
        alignItems: 'center',
        padding: '0 32px',
        zIndex: 5,
      }}>
        {/* Top region: amber dot + state label */}
        <div style={{
          flex: '0 0 auto',
          marginTop: 'calc(env(safe-area-inset-top, 0px) + 56px)',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          gap: 18,
        }}>
          {/* Amber dot — pulses only while a voice line is playing */}
          <motion.span
            aria-hidden
            animate={{
              opacity: speaking ? [0.4, 1, 0.4] : 0.25,
              scale: speaking ? [0.9, 1.15, 0.9] : 1,
            }}
            transition={{
              duration: speaking ? 1.4 : 0.6,
              repeat: speaking ? Infinity : 0,
              ease: 'easeInOut',
            }}
            style={{
              width: 8,
              height: 8,
              borderRadius: '50%',
              background: COLORS.scoreAmber,
              display: 'block',
            }}
          />

          {/* State label */}
          <AnimatePresence mode="wait">
            <motion.div
              key={stateKey}
              initial={{ opacity: 0, y: 4 }}
              animate={{ opacity: hasError ? 1 : 0.75, y: 0 }}
              exit={{ opacity: 0, y: -4 }}
              transition={{ duration: 0.4, ease: 'easeOut' }}
              style={{
                fontFamily: FONTS.serif,
                fontStyle: 'italic',
                fontSize: 14,
                letterSpacing: 0.3,
                color: hasError ? 'var(--ink, #1C1814)' : 'var(--ink-2, #6B5840)',
                textAlign: 'center',
              }}
            >
              {stateLabel}
            </motion.div>
          </AnimatePresence>

          {/* The active question the companion is asking. Reads from
              liveSession; shows only utterances containing '?', extracts
              the question sentence, persists through the user response. */}
          <QuestionDisplay />
        </div>

        {/* The active movement overlay. Each renders its gesture UI over the
            clean cream stage (the sacred-geometry scene was removed) and drives the
            score's commit/advance. */}
        {movementId === 'leanLift' && (
          <LeanLift
            live={score.live}
            committed={score.state.status === 'committed'}
            onCommit={score.commit}
            onAdvance={score.advance}
            subfaces={score.movement?.subfaces}
            cueDimmed={cueDimmed}
          />
        )}
        {movementId === 'listen' && (
          <Listen
            live={score.live}
            committed={score.state.status === 'committed'}
            onCommit={score.commit}
            onAdvance={score.advance}
            subfaces={score.movement?.subfaces}
            cueDimmed={cueDimmed}
          />
        )}
        {movementId === 'rise' && (
          <Rise
            live={score.live}
            committed={score.state.status === 'committed'}
            onCommit={score.commit}
            onAdvance={score.advance}
            cueDimmed={cueDimmed}
          />
        )}
        {movementId === 'face' && (
          <Face
            live={score.live}
            committed={score.state.status === 'committed'}
            onCommit={score.commit}
            onAdvance={score.advance}
            cueDimmed={cueDimmed}
          />
        )}

        {/* The era beat — search a song; its year picks the version.
            No cueDimmed here: era is the one TYPED beat, and its search field,
            results, and skip affordance all have to stay legible after the
            Prompter's line. The spoken ask still plays — the screen just
            doesn't recede behind it. */}
        {movementId === 'era' && (
          <EraSearch
            onPick={(year) => { setEra(year); maybeStartGeneration(); score.advance() }}
            onSkip={() => { maybeStartGeneration(); score.advance() }}
          />
        )}

        {/* The end-of-Act-1 reflection — the spoken reading, centered. */}
        {movementId === 'reflect' && reflectionCaption && (
          <div style={{
            position: 'absolute', inset: 0, zIndex: 6, pointerEvents: 'none',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            padding: '0 36px',
          }}>
            <AnimatePresence mode="wait">
              <motion.div
                key={reflectionCaption}
                initial={{ opacity: 0, y: 6 }}
                animate={{ opacity: 0.9, y: 0 }}
                exit={{ opacity: 0, y: -6 }}
                transition={{ duration: 0.7, ease: 'easeOut' }}
                style={{
                  fontFamily: FONTS.serif, fontStyle: 'italic',
                  fontSize: 19, lineHeight: 1.5,
                  color: 'var(--ink, currentColor)', textAlign: 'center',
                  maxWidth: 340,
                }}
              >
                {reflectionCaption}
              </motion.div>
            </AnimatePresence>
          </div>
        )}

        {/* Bloom — a visual correlate for the room physically opening
            (AdmirerRoom.beginExpansion, ~3500ms) so the app's richest audio
            moment doesn't play under a blank stage. Reuses the amber
            expanding-ring pattern from Rise/Face's strike flash, scaled up to
            the full stage. Purely decorative — no state machine, no gating. */}
        {movementId === 'bloom' && (
          <div style={{
            position: 'absolute', inset: 0, zIndex: 4, pointerEvents: 'none',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            overflow: 'hidden',
          }}>
            {[0, 0.45].map((delay) => (
              <motion.div
                key={delay}
                aria-hidden
                initial={{ opacity: 0.45, scale: 0.12 }}
                animate={{ opacity: 0, scale: 1 }}
                transition={{ duration: 3.4, delay, ease: 'easeOut' }}
                style={{
                  position: 'absolute',
                  width: '86vmin', height: '86vmin',
                  maxWidth: 640, maxHeight: 640,
                  borderRadius: '50%',
                  border: `1px solid ${COLORS.scoreAmber}`,
                }}
              />
            ))}
          </div>
        )}

        {/* Spacer */}
        <div style={{ flex: 1 }} />

        {/* Arrival escape hatch: low-emphasis tap-to-continue shown after 2.5 s
            (or immediately on error). The listener never speaks — this tap is
            the only way out of arrival, so the arc never stalls. */}
        {score.movement?.id === 'arrival' && showArrivalContinue && (
          <div style={{
            flex: '0 0 auto',
            marginBottom: 'calc(env(safe-area-inset-bottom, 0px) + 32px)',
          }}>
            <button
              onClick={() => {
                if (arrivalAdvancedRef.current) return
                arrivalAdvancedRef.current = true
                score.advance()
              }}
              style={{
                fontFamily: FONTS.serif,
                fontStyle: 'italic',
                fontSize: 13,
                letterSpacing: 0.3,
                color: 'var(--ink-2, #6B5840)',
                background: 'transparent',
                border: '1px solid var(--ink-2, #6B5840)',
                borderRadius: 20,
                padding: '6px 18px',
                cursor: 'pointer',
                opacity: 0.7,
              }}
            >
              continue
            </button>
          </div>
        )}
      </div>
    </StageSurface>
  )
}

export default function Admirer({ onNext, getAudioCtx, revealAudioRef }) {
  return (
    <AdmirerInner onNext={onNext} getAudioCtx={getAudioCtx} revealAudioRef={revealAudioRef} />
  )
}
