import { useEffect, useRef, useState, useCallback } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import Paper from '../score/Paper'
import { COLORS, FONTS } from '../score/tokens'
import { appendEntry } from '../lib/sessionStore.js'
import StemPlayer from '../lib/stemPlayer.js'
import { fireMoment, resetMoments } from '../lib/momentBus.js'
import { advanceFormationStage, resetFormationStage } from '../lib/formationStage.js'
import QuestionDisplay from './QuestionDisplay'
import { useAdmirerRoom } from '../hooks/useAdmirerRoom.js'
import { getAvd, resetAvd } from '../lib/avdStore.js'
import { mapAvdToStems } from '../lib/avdToStems.js'
import { avdRecorder } from '../lib/avdRecorder.js'
import { buildSessionRecord } from '../lib/sessionRecord.js'
import { useAttunementScore } from '../hooks/useAttunementScore.js'
import { archetypeRing } from '../lib/archetypeRing.js'
import LeanLift from './attunement/LeanLift'
import Rise from './attunement/Rise'
import Face from './attunement/Face'
import Listen from './attunement/Listen'
import { FRAGMENTS } from '../lib/fragmentBank.js'
import { allClipIds, mirrorClipId, readingClipId, mirrorText, readingText } from '../lib/reflectionScript.js'
import { getReflection, resetReflection } from '../lib/reflectionState.js'

// The Admirer's spoken lines are pre-baked TTS clips in public/admirer/voice/
// (generated by scripts/generate-admirer-voice.js with the Admirer voice).
// Only lines listed here have a clip on disk; others are skipped silently so
// the on-screen movement cues still carry the prompt. The live ElevenLabs agent
// has been fully removed. Includes the welcome + the 18 reflection clips.
const AVAILABLE_VOICE_LINES = new Set(['welcome', ...allClipIds()])

// The Admirer phase. Voice is pre-baked TTS clips played through the HRTF room
// (no live agent). Kept as an inner component for a stable single mount point.
function AdmirerInner({ onNext, getAudioCtx, revealAudioRef }) {
  const [hasError, setHasError] = useState(false)
  // FIX 1 — tap-to-continue escape hatch for the arrival beat.
  const [showArrivalContinue, setShowArrivalContinue] = useState(false)
  const stemsBundleRef = useRef(null)
  const playerRef = useRef(null)
  // Idempotency guard for the orchestra handoff. The score's bloom is the
  // intended trigger; this also makes a stray agent commitEntry call a no-op
  // so the record is persisted and onNext fires exactly once.
  const committedRef = useRef(false)

  // Monotonic token so the last-requested load wins; superseded in-flight
  // loads self-abandon (no orphan started players).
  const loadTokenRef = useRef(0)

  // Load the matched song's stems silently in the background so the Orchestra
  // can pick them up via revealAudioRef without an audio gap. Race-safe: the
  // last call wins; an earlier call that resolves after a newer one has started
  // abandons itself without starting or writing anything.
  const loadStemsSilently = useCallback(async (bundle) => {
    const ctx = getAudioCtx?.()
    if (!ctx) {
      console.warn('[attunement] no audio context — orchestra will fall back to static track')
      return
    }
    const token = ++loadTokenRef.current
    const prev = playerRef.current
    try {
      const player = await StemPlayer.load(ctx, bundle.stems, bundle.masterUrl)
      // A newer load was requested while we were decoding — abandon this one.
      // It was never start()ed, so it has no live audio graph to tear down.
      if (token !== loadTokenRef.current) return
      // Stop the previously-started player (if any) before replacing it.
      if (prev && prev !== player) {
        try { prev.stop?.() } catch { /* ignore */ }
      }
      player.setVolume(0, 0)
      player.start()
      playerRef.current = player
      stemsBundleRef.current = bundle
      if (revealAudioRef) revealAudioRef.current = player
    } catch (e) {
      console.warn('[attunement] StemPlayer.load failed:', e)
    }
  }, [getAudioCtx, revealAudioRef])

  // Speculative silent pre-load during Rise: load the nearest archetype's
  // stems as the in-progress vector resolves. If Face later changes the
  // archetype, onBloom reloads. Skips when the archetype hasn't changed.
  const preloadArchetypeRef = useRef(null)
  const onSpeculativePreload = useCallback((archetypeId) => {
    if (preloadArchetypeRef.current === archetypeId) return
    preloadArchetypeRef.current = archetypeId
    loadStemsSilently(mapAvdToStems(getAvd(), {}))
  }, [loadStemsSilently])

  // When the score finalizes, build + persist the rich session record, then
  // hand off to orchestra. The 600ms delay lets the bloom's expansion ramp
  // breathe before the phase swaps.
  const onCommitEntry = useCallback((entry) => {
    if (committedRef.current) return
    committedRef.current = true
    try {
      const rec = avdRecorder.isRecording() ? avdRecorder.stop(Date.now()) : null
      const bundle = stemsBundleRef.current
      const record = buildSessionRecord({
        startedAt: rec?.startedAt ?? Date.now(),
        endedAt: rec?.endedAt ?? Date.now(),
        finalVector: rec?.finalVector ?? getAvd(),
        avdTrajectory: rec?.trajectory ?? [],
        landing: bundle ? { archetypeId: bundle.archetypeId, variationId: bundle.variationId } : null,
        summary: entry?.summary || '',
        rand: Math.random(),
      })
      appendEntry(record)
    } catch (e) {
      console.warn('[attunement] session record persist failed', e)
    }
    setTimeout(() => {
      // Carry the Admirer's one-line summary forward so App can relay it in
      // the entry message at settle.
      onNext({ stemsBundle: stemsBundleRef.current, summary: entry?.summary })
    }, 600)
  }, [onNext])

  // Whether a pre-baked voice clip is currently playing. Drives the amber dot
  // pulse + the "speaking" state label (replaces the old SDK isSpeaking).
  const [speaking, setSpeaking] = useState(false)
  // The end-of-Act-1 reflection caption (the spoken text, shown on screen).
  const [reflectionCaption, setReflectionCaption] = useState(null)

  // Build A — the spatial room. Plays the Admirer's pre-baked voice clips +
  // the per-movement multi-source playback through an HRTF room. The score
  // drives the room open (setExpansion per movement, beginExpansion at bloom).
  const { beginExpansion, setExpansion, getRoom } = useAdmirerRoom({ getAudioCtx })

  // Play one of the Admirer's pre-baked voice lines through the room. Lines not
  // present in AVAILABLE_VOICE_LINES (no clip on disk yet) resolve immediately
  // so callers/sequences never stall — the on-screen movement cue carries the
  // prompt in that case. onEnded always fires exactly once.
  const playVoiceLine = useCallback((lineId, { onEnded } = {}) => {
    const room = getRoom?.()
    const ctx = getAudioCtx?.()
    if (!room || !ctx || !AVAILABLE_VOICE_LINES.has(lineId)) { onEnded?.(); return }
    let settled = false
    const finish = () => { if (settled) return; settled = true; setSpeaking(false); onEnded?.() }
    fetch(`/admirer/voice/${lineId}.mp3`)
      .then((r) => r.arrayBuffer())
      .then((b) => ctx.decodeAudioData(b))
      .then((buf) => {
        setSpeaking(true)
        room.playVoiceClip(buf, { onEnded: finish })
      })
      .catch((e) => { console.warn('[admirer] voice line failed:', lineId, e); finish() })
  }, [getRoom, getAudioCtx])

  // Score → room expansion: each committed movement nudges the room a notch.
  const onScoreExpansion = useCallback((t) => { setExpansion(t) }, [setExpansion])

  // Score → room reaction. The only audible reaction kept is the Rise
  // down-stroke transient (markBeat); spoken reactions are gone with the agent.
  const onScoreReact = useCallback((movementId, payload) => {
    if (movementId === 'rise' && payload.downbeat) {
      roomHandleRef.current?.markBeat?.(payload.intensity ?? 1)
    }
  }, [])

  // Score → asking: when a movement begins, play that movement's pre-baked ask
  // clip if one exists. Until the per-movement asks are authored + generated,
  // this is a silent no-op and the overlay's on-screen cue carries the prompt.
  const onScoreAsk = useCallback((movementId) => {
    playVoiceLine(`ask-${movementId}`)
  }, [playVoiceLine])

  // Score → bloom (the act-1 → act-2 handoff). Ensure the faced archetype's
  // stems are the loaded ones, snap the geometry fully formed, animate the
  // room open, then build + persist the record and hand off to Orchestra
  // (reusing onCommitEntry's body — the seam the Orchestra depends on).
  // FIX 2 — async: await the load so the 600ms onNext can't race a slow reload.
  const onBloom = useCallback(async () => {
    const bundle = mapAvdToStems(getAvd(), {})
    // Gate the commit on the load so the 600ms onNext can't race a slow
    // reload (which would let Orchestra detach a stale/empty player).
    const needLoad = !playerRef.current || bundle.archetypeId !== stemsBundleRef.current?.archetypeId
    if (needLoad) await loadStemsSilently(bundle)
    // Editorial moment: snap to fully formed; front figure fades in over the
    // handoff. eventIds keep both safe against re-fire.
    fireMoment(1.0, 'startGeneration')
    advanceFormationStage(2)
    beginExpansion()
    onCommitEntry({ summary: '' })
  }, [loadStemsSilently, beginExpansion, onCommitEntry])

  const score = useAttunementScore({
    onExpansion: onScoreExpansion,
    onSpeculativePreload,
    onBloom,
    onReact: onScoreReact,
    onAsk: onScoreAsk,
  })

  // Arrival choreography: footsteps walk up (far → close), then the Admirer
  // speaks the welcome from the seat where they arrived, then we advance into
  // the first movement (leanLift). Gated on the room being live — getRoom() is
  // null until the room's build effect runs, so we retry briefly. Runs once.
  const arrivalStartedRef = useRef(false)
  const advanceRef = useRef(null)
  useEffect(() => { advanceRef.current = score.advance })
  useEffect(() => {
    let cancelled = false
    let tries = 0
    let timer = null
    const begin = () => {
      if (cancelled || arrivalStartedRef.current) return
      const room = getRoom?.()
      const ctx = getAudioCtx?.()
      if (!room || !ctx) {
        if (tries++ < 40) timer = setTimeout(begin, 100)
        else setHasError(true) // no audio after ~4s — surface the escape hatch
        return
      }
      arrivalStartedRef.current = true
      const toWelcome = () => {
        if (cancelled) return
        fireMoment(0.12, 'welcome')
        playVoiceLine('welcome', { onEnded: () => { if (!cancelled) advanceRef.current?.() } })
      }
      fetch('/admirer/footsteps.mp3')
        .then((r) => r.arrayBuffer())
        .then((b) => ctx.decodeAudioData(b))
        .then((buf) => { if (!cancelled) room.playFootsteps(buf, { onEnded: toWelcome }) })
        .catch(() => toWelcome()) // no footsteps clip — still welcome
    }
    begin()
    return () => { cancelled = true; if (timer) clearTimeout(timer) }
  }, [getRoom, getAudioCtx, playVoiceLine])

  // End-of-Act-1 reflection: on entering the 'reflect' beat, narrate the mirror
  // (what the listener's body chose) then the faced world's reading, then
  // advance into bloom. Two pre-baked clips stitched at a sentence boundary; the
  // caption shows the spoken text. Runs once. Deferred via setTimeout(0) so no
  // synchronous setState in the effect body (react-hooks lint).
  const reflectStartedRef = useRef(false)
  useEffect(() => {
    if (score.movement?.id !== 'reflect' || reflectStartedRef.current) return
    reflectStartedRef.current = true
    let cancelled = false
    const t = setTimeout(() => {
      if (cancelled) return
      const r = getReflection()
      const warmth = r.warmth || 'warm'
      const depth = r.depth || 'open'
      const energy = r.energy || 'low'
      const world = r.world || 'hearth-keeper'
      setReflectionCaption(mirrorText(warmth, depth, energy))
      playVoiceLine(mirrorClipId(warmth, depth, energy), {
        onEnded: () => {
          if (cancelled) return
          setReflectionCaption(readingText(world))
          playVoiceLine(readingClipId(world), {
            onEnded: () => { if (!cancelled) advanceRef.current?.() },
          })
        },
      })
    }, 0)
    return () => { cancelled = true; clearTimeout(t) }
  }, [score.movement?.id, playVoiceLine])

  // Arrival escape hatch: a low-emphasis "continue" appears only as a safety
  // net — immediately on error, or if the welcome hasn't advanced us out of
  // arrival after a generous wait — so the arc can never permanently stall.
  // setState is deferred via setTimeout to satisfy react-hooks/set-state-in-effect.
  useEffect(() => {
    const movId = score.movement?.id
    if (movId !== 'arrival') {
      const t = setTimeout(() => setShowArrivalContinue(false), 0)
      return () => clearTimeout(t)
    }
    if (hasError) {
      const t = setTimeout(() => setShowArrivalContinue(true), 0)
      return () => clearTimeout(t)
    }
    const t = setTimeout(() => setShowArrivalContinue(true), 32000)
    return () => clearTimeout(t)
  }, [score.movement?.id, hasError])

  // Per-movement room playback: start/stop the right multi-source handle as
  // the movement changes. Fragment masters stand in as textures for the Lean
  // pair / Face ring / Rise bed (assets refined later — spec §11).
  const roomHandleRef = useRef(null)
  useEffect(() => {
    const room = getRoom()
    const ctx = getAudioCtx?.()
    if (!room || !ctx) return undefined
    let cancelled = false
    const decode = (url) => fetch(url).then((r) => r.arrayBuffer()).then((b) => ctx.decodeAudioData(b))

    const start = async () => {
      try {
        if (score.movement?.id === 'leanLift') {
          const [l, r] = await Promise.all([
            decode(FRAGMENTS[2].url), // shadow-piano-late (cold)
            decode(FRAGMENTS[0].url), // warm-acoustic-now (warm)
          ])
          if (cancelled) return
          roomHandleRef.current = room.playTexturePair(l, r)
        } else if (score.movement?.id === 'listen') {
          const bed = await decode(FRAGMENTS[1].url) // a world fragment to shape
          if (cancelled) return
          roomHandleRef.current = room.playFilteredBed(bed)
        } else if (score.movement?.id === 'rise') {
          const bed = await decode(FRAGMENTS[4].url) // lifted-cinematic
          if (cancelled) return
          roomHandleRef.current = room.playRiseBed(bed)
        } else if (score.movement?.id === 'face') {
          const ring = archetypeRing()
          const entries = await Promise.all(ring.map(async (rr, i) => ({
            azimuthDeg: rr.azimuthDeg,
            buffer: await decode(FRAGMENTS[i % FRAGMENTS.length].url),
          })))
          if (cancelled) return
          roomHandleRef.current = room.playRingSources(entries)
        }
      } catch (e) {
        console.warn('[attunement] room playback failed for', score.movement?.id, e)
      }
    }
    start()
    return () => {
      cancelled = true
      try { roomHandleRef.current?.stop() } catch { /* ignore */ }
      roomHandleRef.current = null
    }
  }, [score.movement?.id, getRoom, getAudioCtx])

  // Drive the active room handle from the live gesture each frame.
  useEffect(() => {
    let raf = 0
    let mounted = true
    const tick = () => {
      if (!mounted) return
      const h = roomHandleRef.current
      if (h) {
        if (score.movement?.id === 'leanLift' && h.setBalance) {
          // Post-commit, hold the crossfade at the chosen side so a relaxing
          // wrist doesn't slide the warm/cold balance back toward center.
          const cb = score.live.current.committedBalance
          if (typeof cb === 'number') h.setBalance(Math.sign(cb) || 0)
          else h.setBalance((score.live.current.pan - 0.5) * 2)
        }
        if (score.movement?.id === 'listen' && h.setBrightness) {
          // Tilt forward (low filterNorm) DARKENS the bed — matching the
          // Orchestra (beta → filter cutoff). Post-commit hold it at the chosen
          // extreme so a relaxing wrist doesn't drift the brightness.
          const cbr = score.live.current.committedBrightness
          if (typeof cbr === 'number') h.setBrightness(cbr)
          else h.setBrightness(score.live.current.filterNorm ?? 0.5)
        }
        // FIX 3 — drive Rise audio reactivity each frame.
        if (score.movement?.id === 'rise' && h.setSwell) {
          h.setSwell(score.live.current.swell ?? 0)
        }
        if (score.movement?.id === 'face' && h.spotlight) {
          h.spotlight(score.live.current.relYaw)
        }
      }
      raf = requestAnimationFrame(tick)
    }
    raf = requestAnimationFrame(tick)
    return () => { mounted = false; cancelAnimationFrame(raf) }
  }, [score.movement?.id, score.live])

  // Editorial moment dispatcher + session lifecycle. Each rite starts with
  // the release at 0 (resetMoments) plus an immediate 8% pre-release. The
  // 'mount' eventId makes this idempotent. Also resets the AVD vector and
  // starts the ~1Hz AVD trajectory recorder; cleanup stops it + resets.
  useEffect(() => {
    resetMoments()
    resetFormationStage()
    resetReflection()
    fireMoment(0.08, 'mount')
    resetAvd()
    avdRecorder.start(Date.now())
    return () => {
      if (avdRecorder.isRecording()) avdRecorder.stop(Date.now())
      resetAvd()
    }
  }, [])

  // Stop the orphan StemPlayer on unmount if the rite was abandoned.
  useEffect(() => {
    return () => {
      // Only stop the player if the rite was ABANDONED (not committed). On a
      // committed bloom this player is the live handoff — Orchestra mounts next
      // (AnimatePresence mode="wait" unmounts us first) and calls
      // detachAndGetSources() on it; stopping it here nulls its sources and the
      // song dies at the seam.
      const player = playerRef.current
      if (player && !committedRef.current && revealAudioRef?.current === player) {
        try { player.stop?.() } catch { /* ignore */ }
        if (revealAudioRef) revealAudioRef.current = null
      }
      playerRef.current = null
    }
  }, [])

  // Derive the visible state label from voice playback + the active movement.
  const movementId = score.movement?.id
  let stateLabel
  let stateKey
  if (hasError) {
    stateLabel = 'the Admirer could not arrive. try again later.'
    stateKey = 'error'
  } else if (movementId === 'reflect') {
    // The reflection caption carries the words; keep the label quiet.
    stateLabel = ''
    stateKey = 'reflect'
  } else if (speaking) {
    stateLabel = 'speaking'
    stateKey = 'speaking'
  } else if (movementId === 'arrival') {
    // The Admirer is walking up / about to speak the welcome.
    stateLabel = 'arriving'
    stateKey = 'arriving'
  } else if (movementId === 'leanLift') {
    stateLabel = 'lean toward what pulls'
    stateKey = 'leanLift'
  } else if (movementId === 'listen') {
    stateLabel = 'listen'
    stateKey = 'listen'
  } else if (movementId === 'rise') {
    stateLabel = 'let it rise'
    stateKey = 'rise'
  } else if (movementId === 'face') {
    stateLabel = 'face the room'
    stateKey = 'face'
  } else {
    // bloom / handoff — fall silent
    stateLabel = ''
    stateKey = 'bloom'
  }

  return (
    <Paper variant="cream">
      <div style={{
        position: 'absolute', inset: 0,
        display: 'flex', flexDirection: 'column',
        alignItems: 'center',
        padding: '0 32px',
        zIndex: 5,
      }}>
        {/* Top region: amber dot + state label */}
        <div style={{
          flex: '0 0 auto',
          marginTop: 'calc(env(safe-area-inset-top, 0px) + 56px)',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          gap: 18,
        }}>
          {/* Amber dot — pulses only while a voice line is playing */}
          <motion.span
            aria-hidden
            animate={{
              opacity: speaking ? [0.4, 1, 0.4] : 0.25,
              scale: speaking ? [0.9, 1.15, 0.9] : 1,
            }}
            transition={{
              duration: speaking ? 1.4 : 0.6,
              repeat: speaking ? Infinity : 0,
              ease: 'easeInOut',
            }}
            style={{
              width: 8,
              height: 8,
              borderRadius: '50%',
              background: COLORS.scoreAmber,
              display: 'block',
            }}
          />

          {/* State label */}
          <AnimatePresence mode="wait">
            <motion.div
              key={stateKey}
              initial={{ opacity: 0, y: 4 }}
              animate={{ opacity: hasError ? 1 : 0.75, y: 0 }}
              exit={{ opacity: 0, y: -4 }}
              transition={{ duration: 0.4, ease: 'easeOut' }}
              style={{
                fontFamily: FONTS.serif,
                fontStyle: 'italic',
                fontSize: 14,
                letterSpacing: 0.3,
                color: hasError ? COLORS.inkCream : COLORS.inkCreamSecondary,
                textAlign: 'center',
              }}
            >
              {stateLabel}
            </motion.div>
          </AnimatePresence>

          {/* The active question the companion is asking. Reads from
              liveSession; shows only utterances containing '?', extracts
              the question sentence, persists through the user response. */}
          <QuestionDisplay />
        </div>

        {/* The active movement overlay. Each renders its gesture UI over the
            clean cream stage (the sacred-geometry scene was removed) and drives the
            score's commit/advance. */}
        {movementId === 'leanLift' && (
          <LeanLift
            live={score.live}
            committed={score.state.status === 'committed'}
            onCommit={score.commit}
            onAdvance={score.advance}
          />
        )}
        {movementId === 'listen' && (
          <Listen
            live={score.live}
            committed={score.state.status === 'committed'}
            onCommit={score.commit}
            onAdvance={score.advance}
          />
        )}
        {movementId === 'rise' && (
          <Rise
            live={score.live}
            committed={score.state.status === 'committed'}
            onCommit={score.commit}
            onAdvance={score.advance}
          />
        )}
        {movementId === 'face' && (
          <Face
            live={score.live}
            committed={score.state.status === 'committed'}
            onCommit={score.commit}
            onAdvance={score.advance}
          />
        )}

        {/* The end-of-Act-1 reflection — the spoken reading, centered. */}
        {movementId === 'reflect' && reflectionCaption && (
          <div style={{
            position: 'absolute', inset: 0, zIndex: 6, pointerEvents: 'none',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            padding: '0 36px',
          }}>
            <AnimatePresence mode="wait">
              <motion.div
                key={reflectionCaption}
                initial={{ opacity: 0, y: 6 }}
                animate={{ opacity: 0.9, y: 0 }}
                exit={{ opacity: 0, y: -6 }}
                transition={{ duration: 0.7, ease: 'easeOut' }}
                style={{
                  fontFamily: FONTS.serif, fontStyle: 'italic',
                  fontSize: 19, lineHeight: 1.5,
                  color: 'var(--ink, currentColor)', textAlign: 'center',
                  maxWidth: 340,
                }}
              >
                {reflectionCaption}
              </motion.div>
            </AnimatePresence>
          </div>
        )}

        {/* Spacer */}
        <div style={{ flex: 1 }} />

        {/* Arrival escape hatch: low-emphasis tap-to-continue shown after 2.5 s
            (or immediately on error). The listener never speaks — this tap is
            the only way out of arrival, so the arc never stalls. */}
        {score.movement?.id === 'arrival' && showArrivalContinue && (
          <div style={{
            flex: '0 0 auto',
            marginBottom: 'calc(env(safe-area-inset-bottom, 0px) + 32px)',
          }}>
            <button
              onClick={() => score.advance()}
              style={{
                fontFamily: FONTS.serif,
                fontStyle: 'italic',
                fontSize: 13,
                letterSpacing: 0.3,
                color: COLORS.inkCreamSecondary,
                background: 'transparent',
                border: `1px solid ${COLORS.inkCreamSecondary}`,
                borderRadius: 20,
                padding: '6px 18px',
                cursor: 'pointer',
                opacity: 0.7,
              }}
            >
              continue
            </button>
          </div>
        )}
      </div>
    </Paper>
  )
}

export default function Admirer({ onNext, getAudioCtx, revealAudioRef }) {
  return (
    <AdmirerInner onNext={onNext} getAudioCtx={getAudioCtx} revealAudioRef={revealAudioRef} />
  )
}
